version: 0.2
phases:
  build:
    commands:
       - cd $WORKING_DIRECTORY
      #  - echo $BACKEND >> backend.tf.json
       - terraform init -backend-config=backend.tfvars
       - |
         if [[ "$CONFIRM_DESTROY" == "0" ]]; then
           terraform plan
         else
           terraform plan -destroy
         fi