version: 0.2
phases:
  build:
    commands:
       - cd $WORKING_DIRECTORY
       - terraform init -backend-config=backend.tfvars
       - |
         if [[ "$TF_DESTROY" == "0" ]]; then
           terraform apply -auto-approve -var-file=vars.tfvars
         else
           terraform destroy -auto-approve -var-file=vars.tfvars
         fi